/**
 * One-page Letter PDF investigator sheet via pdfmake.
 * Original layout, no Chaosium trade dress. Client-side only.
 *
 * `buildDocDefinition` is pure — exported for unit testing without loading pdfmake.
 * `generatePDF` is the thin browser-only wrapper that actually renders.
 */

import type { CoCCharacterData } from '$lib/types/character';
import type {
	CoCContentPack,
	CoCSkillDefinition,
	CoCOccupationDefinition
} from '$lib/types/content-pack';
import { ALL_CHARACTERISTICS, CHARACTERISTIC_LABELS } from '$lib/types/common';
import { halfValue, fifthValue } from '$lib/engine/characteristics';
import {
	BACKSTORY_FIELDS,
	BACKSTORY_LABEL_BY_KEY,
	PDF_BACKSTORY_PRIMARY_KEYS,
	PDF_BACKSTORY_PRIORITY_KEYS,
	type BackstoryKey
} from '$lib/engine/backstory';
import {
	buildSkillRows,
	distributeIntoColumns,
	findOccupation,
	truncate,
	type SkillRow
} from './pdf-helpers';

// AA-safe text tokens (preserved from previous export).
const PDF_INK = '#1a1a1a';
const PDF_TEXT_SECONDARY = '#3a3a3a';
const PDF_LABEL = '#444444';
const PDF_FOOTER = '#555555';

// Period accent — burgundy section bands, white uppercase text on top.
const PDF_BANNER_FILL = '#5C1A1B';
const PDF_CHARACTERISTICS_CORNER_FILL = '#000000';
const PDF_BANNER_TEXT = '#ffffff';
const PDF_RULE = '#8a8a8a';
const PDF_BLANK_SLOT = '#777777';
// Zebra fill for skill rows — warm parchment, ~3% darker than white.
// Subtle in color, prints as a barely-perceptible gray in grayscale.
const PDF_ZEBRA = '#f6f0eb';
/** Alternating fills for PDF backstory subsections (readable on screen / print). */
const PDF_BACKSTORY_STRIPE_A = '#ffffff';
const PDF_BACKSTORY_STRIPE_B = '#f3f2f1';

const DISCLAIMER =
	'This is unofficial Fan Content, not approved/endorsed by Chaosium. Call of Cthulhu is a registered trademark of Chaosium Inc. Generated by Miskatonic University Registrar.';

const SKILL_COLUMNS = 3;
const NAME_TRUNCATE = 48;
const BACKSTORY_VALUE_TRUNCATE = 128;
const EQUIPMENT_TRUNCATE = 240;
const MAX_WEAPON_ROWS = 6;

function getEraLabel(era: string, contentPack: CoCContentPack): string {
	return contentPack.eras.find((e) => e.id === era)?.name ?? era;
}

let pdfMakeInstance: any = null;

async function getPdfMake() {
	if (pdfMakeInstance) return pdfMakeInstance;
	const pdfMake = (await import('pdfmake/build/pdfmake')).default;
	const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
	pdfMake.addVirtualFileSystem(pdfFonts);
	pdfMakeInstance = pdfMake;
	return pdfMake;
}

export async function generatePDF(
	character: CoCCharacterData,
	occupationName: string,
	skills: CoCSkillDefinition[],
	occupations: CoCOccupationDefinition[],
	contentPack: CoCContentPack
): Promise<Uint8Array> {
	const docDefinition = buildDocDefinition(character, occupationName, skills, occupations, contentPack);
	const pdfMake = await getPdfMake();
	const pdfDoc = pdfMake.createPdf(docDefinition);
	return await pdfDoc.getBuffer();
}

export function buildDocDefinition(
	character: CoCCharacterData,
	occupationName: string,
	skills: CoCSkillDefinition[],
	occupations: CoCOccupationDefinition[],
	contentPack: CoCContentPack
): Record<string, unknown> {
	const occupation = findOccupation(occupations, character.occupation?.occupationId);
	const skillRows = buildSkillRows(character, skills, occupation);

	return {
		pageSize: 'LETTER',
		pageMargins: [28, 28, 28, 36],
		footer: {
			text: DISCLAIMER,
			fontSize: 6,
			margin: [28, 8, 28, 0],
			color: PDF_FOOTER,
			alignment: 'center' as const
		},
		content: [
			buildHeader(character, occupationName, contentPack),
			{ text: '', margin: [0, 4, 0, 0] },
			buildStatsRow(character),
			{ text: '', margin: [0, 6, 0, 0] },
			buildSkillsSection(skillRows)
		],
		defaultStyle: { fontSize: 8, lineHeight: 1.2, color: PDF_INK },
		styles: {
			titleName: { fontSize: 16, bold: true },
			subtitle: { fontSize: 8, color: PDF_TEXT_SECONDARY },
			banner: {
				fontSize: 8,
				bold: true,
				color: PDF_BANNER_TEXT,
				fillColor: PDF_BANNER_FILL,
				lineHeight: 1,
				margin: [0, 0, 0, 0]
			},
			label: { fontSize: 6, color: PDF_LABEL, bold: true },
			statValue: { fontSize: 13, bold: true, alignment: 'center' as const },
			statSub: { fontSize: 7, color: PDF_TEXT_SECONDARY, alignment: 'center' as const },
			trackerValue: { fontSize: 11, bold: true, alignment: 'center' as const, lineHeight: 1 },
			trackerLabel: {
				fontSize: 6,
				color: PDF_LABEL,
				bold: true,
				alignment: 'center' as const,
				lineHeight: 1
			},
			skillName: { fontSize: 8.5 },
			skillBlank: { fontSize: 8.5, italics: true, color: PDF_BLANK_SLOT },
			skillValue: { fontSize: 8.5, bold: true, alignment: 'right' as const },
			skillSub: { fontSize: 7, color: PDF_TEXT_SECONDARY, alignment: 'right' as const },
			fieldLabel: { fontSize: 6, color: PDF_LABEL, bold: true },
			fieldValue: { fontSize: 7.5 },
			backstoryLabel: { fontSize: 5.6, color: PDF_BANNER_FILL, bold: true },
			backstoryValue: { fontSize: 6.4, lineHeight: 1.05 }
		}
	};
}

// --- Sections ---

function buildHeader(c: CoCCharacterData, occupationName: string, contentPack: CoCContentPack) {
	const name = truncate(c.name || 'Unnamed Investigator', NAME_TRUNCATE);
	const subtitleParts = [
		occupationName,
		`Age ${c.age}`,
		`${getEraLabel(c.era, contentPack)} Era`,
		c.residence,
		c.birthplace ? `b. ${c.birthplace}` : '',
		c.pronouns
	].filter(Boolean);

	return {
		stack: [
			{ text: name, style: 'titleName' },
			{ text: subtitleParts.join('  ·  '), style: 'subtitle' }
		]
	};
}

function bannerCell(text: string) {
	// Single-cell table that gives us a filled section header bar.
	return {
		table: {
			widths: ['*'],
			body: [[{ text: text.toUpperCase(), style: 'banner', margin: [4, 3, 4, 1] }]]
		},
		layout: {
			hLineWidth: () => 0,
			vLineWidth: () => 0,
			fillColor: () => PDF_BANNER_FILL,
			paddingLeft: () => 0,
			paddingRight: () => 0,
			paddingTop: () => 0,
			paddingBottom: () => 0
		},
		margin: [0, 0, 0, 2] as [number, number, number, number]
	};
}

function buildStatsRow(c: CoCCharacterData) {
	return {
		columns: [
			{
				width: '*',
				stack: [
					bannerCell('Characteristics'),
					buildCharacteristicsTable(c),
					{ text: '', margin: [0, 6, 0, 0] as [number, number, number, number] },
					buildCombatAndPossessions(c)
				]
			},
			{ width: 12, text: '' },
			{
				width: '*',
				stack: [
					bannerCell('Attributes'),
					buildTrackersGrid(c),
					{ text: '', margin: [0, 4, 0, 0] as [number, number, number, number] },
					bannerCell('Backstory'),
					buildBackstoryGrid(c),
					buildFinancesRow(c)
				]
			}
		]
	};
}

function buildCharacteristicsTable(c: CoCCharacterData) {
	const headerCellStyle = {
		fontSize: 8,
		color: PDF_LABEL,
		bold: true,
		alignment: 'center' as const
	};
	const headerRow = [
		// Top-left "unused" corner prints as a solid black anchor.
		{ text: '', fillColor: PDF_CHARACTERISTICS_CORNER_FILL },
		{ text: 'Reg', ...headerCellStyle },
		{ text: 'Half', ...headerCellStyle },
		{ text: 'Fifth', ...headerCellStyle }
	];
	// Vertical centering: the regular value (statValue, fontSize 13) drives row
	// height. Smaller cells get a top margin = (rowHeight - cellHeight) / 2 so
	// they read as centered rather than top-aligned.
	const body = [
		headerRow,
		...ALL_CHARACTERISTICS.map((id) => {
			const v = c.characteristics.values[id];
			return [
				{
					text: CHARACTERISTIC_LABELS[id],
					fontSize: 11,
					bold: true,
					alignment: 'center' as const,
					margin: [0, 2, 0, 0] as [number, number, number, number]
				},
				{ text: String(v), style: 'statValue' },
				{
					text: String(halfValue(v)),
					fontSize: 12,
					alignment: 'center' as const,
					color: PDF_TEXT_SECONDARY,
					margin: [0, 1, 0, 0] as [number, number, number, number]
				},
				{
					text: String(fifthValue(v)),
					fontSize: 12,
					alignment: 'center' as const,
					color: PDF_TEXT_SECONDARY,
					margin: [0, 1, 0, 0] as [number, number, number, number]
				}
			];
		})
	];

	return {
		table: { widths: [90, '*', 30, 30], body },
		layout: {
			hLineWidth: () => 0.5,
			vLineWidth: () => 0.5,
			hLineColor: () => PDF_RULE,
			vLineColor: () => PDF_RULE,
			paddingLeft: () => 2,
			paddingRight: () => 2,
			paddingTop: () => 1,
			paddingBottom: () => 1
		}
	};
}

function trackerBox(label: string, current: number | string, max?: number | string) {
	const valueText =
		max !== undefined && max !== '' ? `${current} / ${max}` : String(current);
	return {
		table: {
			widths: ['*'],
			body: [
				[
					{
						text: label.toUpperCase(),
						style: 'trackerLabel',
						margin: [0, 0, 0, 0] as [number, number, number, number]
					}
				],
				[
					{
						text: valueText,
						style: 'trackerValue',
						margin: [0, 0, 0, 0] as [number, number, number, number]
					}
				]
			]
		},
		layout: {
			hLineWidth: () => 0.75,
			vLineWidth: () => 0.75,
			hLineColor: () => PDF_INK,
			vLineColor: () => PDF_INK,
			paddingLeft: () => 0,
			paddingRight: () => 0,
			paddingTop: (rowIndex: number) => (rowIndex === 0 ? 2 : 3),
			paddingBottom: (rowIndex: number) => (rowIndex === 0 ? 2 : 3)
		}
	};
}

function buildTrackersGrid(c: CoCCharacterData) {
	const d = c.derivedStats;
	const cell = (col: any) => ({ width: '*', stack: [col] });

	return {
		stack: [
			{
				columns: [
					cell(trackerBox('Hit Points', d.hp.current, d.hp.max)),
					{ width: 6, text: '' },
					cell(trackerBox('Magic Points', d.mp.current, d.mp.max)),
					{ width: 6, text: '' },
					cell(trackerBox('Sanity', d.sanity.current, d.sanity.max))
				],
				margin: [0, 0, 0, 4] as [number, number, number, number]
			},
			{
				columns: [
					cell(trackerBox('Luck', d.luck.current)),
					{ width: 4, text: '' },
					cell(trackerBox('Damage Bonus', d.damageBonus)),
					{ width: 4, text: '' },
					cell(trackerBox('Build', d.build)),
					{ width: 4, text: '' },
					cell(trackerBox('Move', d.moveRate))
				]
			}
		]
	};
}

function formatRowName(row: SkillRow): string {
	const marker = row.isOccupation ? '● ' : row.isImproved ? '◐ ' : '○ ';
	return marker + row.displayName;
}

function buildSkillsSection(rows: SkillRow[]) {
	// Do not print the grey italic “(________)” blank specialization slots on the PDF.
	const printableRows = rows.filter((r) => !r.isBlankSlot);
	const columns = distributeIntoColumns(printableRows, SKILL_COLUMNS);

	const renderColumn = (colRows: SkillRow[]) => {
		const body: Array<Array<{ text: string; style: string }>> = colRows.map((row) => {
			const valueText = row.value === null ? '' : `${row.value}`;
			const halfText = row.value === null ? '' : `${halfValue(row.value)}`;
			const fifthText = row.value === null ? '' : `${fifthValue(row.value)}`;
			return [
				{
					text: formatRowName(row),
					style: row.isBlankSlot ? 'skillBlank' : 'skillName'
				},
				{ text: valueText, style: 'skillValue' },
				{ text: halfText, style: 'skillSub' },
				{ text: fifthText, style: 'skillSub' }
			];
		});
		// Pad shorter columns to keep heights aligned.
		const targetLength = Math.max(...columns.map((c) => c.length));
		while (body.length < targetLength) {
			body.push([
				{ text: '', style: 'skillName' },
				{ text: '', style: 'skillValue' },
				{ text: '', style: 'skillSub' },
				{ text: '', style: 'skillSub' }
			]);
		}
		return {
			table: { widths: ['*', 18, 14, 14], body },
			layout: {
				hLineWidth: () => 0,
				vLineWidth: () => 0,
				fillColor: (rowIndex: number) =>
					rowIndex % 2 === 1 ? PDF_ZEBRA : null,
				paddingLeft: () => 3,
				paddingRight: () => 3,
				paddingTop: () => 1,
				paddingBottom: () => 1
			}
		};
	};

	const cols: any[] = [];
	columns.forEach((col, i) => {
		cols.push({ width: '*', stack: [renderColumn(col)] });
		if (i < columns.length - 1) cols.push({ width: 6, text: '' });
	});

	return { stack: [bannerCell('Investigator Skills'), { columns: cols }] };
}

function buildWeaponsAndFinances(c: CoCCharacterData) {
	const eq = c.equipment;
	const stack: any[] = [bannerCell('Combat & Possessions')];

	// Combined table: weapons + gear in one layout.
	// We cap total rows to keep the left column bounded.
	const MAX_ROWS = MAX_WEAPON_ROWS;
	const weaponRows = eq.weapons.slice(0, MAX_ROWS);
	const remaining = Math.max(0, MAX_ROWS - weaponRows.length);
	const gearRows = eq.items.slice(0, remaining);

	const overflowWeapons = Math.max(0, eq.weapons.length - weaponRows.length);
	const overflowGear = Math.max(0, eq.items.length - gearRows.length);

	const body: any[] = [
		[
			{ text: 'Item', style: 'label' },
			{ text: 'Damage', style: 'label' },
			{ text: 'Range', style: 'label' },
			{ text: 'Atk', style: 'label' }
		],
		...weaponRows.map((w) => [
			{ text: truncate(w.name, 28), fontSize: 7 },
			{ text: w.damage, fontSize: 7 },
			{ text: w.range, fontSize: 7 },
			{ text: w.attacksPerRound, fontSize: 7 }
		]),
		...gearRows.map((i) => [
			{ text: truncate(i.name, 28), fontSize: 7 },
			{ text: '', fontSize: 7, color: PDF_TEXT_SECONDARY },
			{ text: '', fontSize: 7, color: PDF_TEXT_SECONDARY },
			{ text: '', fontSize: 7, color: PDF_TEXT_SECONDARY }
		])
	];

	if (overflowWeapons + overflowGear > 0) {
		const parts = [
			overflowWeapons > 0 ? `+${overflowWeapons} weapon${overflowWeapons === 1 ? '' : 's'}` : '',
			overflowGear > 0 ? `+${overflowGear} item${overflowGear === 1 ? '' : 's'}` : ''
		].filter(Boolean);
		body.push([
			{ text: `${parts.join(', ')} not shown`, fontSize: 6, color: PDF_FOOTER, italics: true } as any,
			{ text: '' },
			{ text: '' },
			{ text: '' }
		]);
	}

	if (weaponRows.length > 0 || gearRows.length > 0) {
		stack.push({
			table: { widths: ['*', 60, 50, 30], body },
			layout: {
				hLineWidth: () => 0.25,
				vLineWidth: () => 0.25,
				hLineColor: () => PDF_RULE,
				vLineColor: () => PDF_RULE,
				paddingLeft: () => 3,
				paddingRight: () => 3,
				paddingTop: () => 1,
				paddingBottom: () => 1
			},
			margin: [0, 0, 0, 4] as [number, number, number, number]
		});
	}

	return { stack };
}

function buildFinancesRow(c: CoCCharacterData) {
	const eq = c.equipment;
	const financeParts = [
		eq.livingStandard ? `Living: ${eq.livingStandard}` : '',
		eq.spendingLevel ? `Spend: $${eq.spendingLevel.toLocaleString()}` : '',
		`Cash: $${(eq.cash || 0).toLocaleString()}`,
		eq.assetsLabel ? `Assets: ${eq.assetsLabel}` : ''
	].filter(Boolean);

	return {
		columns: [
			{ text: 'FINANCES', style: 'fieldLabel', width: 50 },
			{ text: financeParts.join('  ·  '), style: 'fieldValue' }
		],
		margin: [0, 4, 0, 0] as [number, number, number, number]
	};
}

function buildCombatAndPossessions(c: CoCCharacterData) {
	// Same content as the old bottom section, but placed under Characteristics so
	// the left column uses space that would otherwise be blank.
	return buildWeaponsAndFinances(c);
}

function normalizeBackstoryValue(raw: string): string {
	const trimmed = raw.trim();
	if (!trimmed) return '—';
	return trimmed.replace(/\s+/g, ' ');
}

function backstoryPairsForPdf(c: CoCCharacterData): Array<{ key: BackstoryKey; label: string; value: string }> {
	const valueByKey = (k: BackstoryKey) => normalizeBackstoryValue(c.backstory[k] ?? '');

	// Prefer fewer fields with more text:
	// - pick from an explicit priority list, skipping empties
	// - then (only if space remains) fill from remaining non-empty fields
	const priority = PDF_BACKSTORY_PRIORITY_KEYS.map((key) => ({
		key,
		label: BACKSTORY_LABEL_BY_KEY[key],
		value: truncate(valueByKey(key), BACKSTORY_VALUE_TRUNCATE)
	})).filter((f) => f.value !== '—');

	const prioritySet = new Set<BackstoryKey>(PDF_BACKSTORY_PRIORITY_KEYS as BackstoryKey[]);
	const remainder = BACKSTORY_FIELDS
		.map((f) => f.key)
		.filter((k): k is BackstoryKey => !prioritySet.has(k))
		.map((key) => ({
			key,
			label: BACKSTORY_LABEL_BY_KEY[key],
			value: truncate(valueByKey(key), BACKSTORY_VALUE_TRUNCATE)
		}))
		.filter((f) => f.value !== '—');

	// Keep at least the historical four if they have content, even if they weren't in the priority list for some reason.
	const historical = PDF_BACKSTORY_PRIMARY_KEYS.map((key) => ({
		key,
		label: BACKSTORY_LABEL_BY_KEY[key],
		value: truncate(valueByKey(key), BACKSTORY_VALUE_TRUNCATE)
	})).filter((f) => f.value !== '—' && !prioritySet.has(f.key));

	return [...priority, ...historical, ...remainder];
}

/** Checkerboard shading: `(row + col) % 2` — top-left unshaded, top-right shaded, swap each row down. */
function backstoryCell(
	def: { label: string; value: string },
	rowIdx: number,
	colIdx: 0 | 1
): any {
	const fill =
		(rowIdx + colIdx) % 2 === 0 ? PDF_BACKSTORY_STRIPE_A : PDF_BACKSTORY_STRIPE_B;
	return {
		table: {
			widths: ['*'],
			body: [
				[
					{
						text: def.label.toUpperCase(),
						style: 'backstoryLabel',
						margin: [0, 0, 0, 0],
						fillColor: fill
					}
				],
				[{ text: def.value, style: 'backstoryValue', fillColor: fill }]
			]
		},
		layout: {
			hLineWidth: () => 0,
			vLineWidth: () => 0,
			paddingLeft: () => 2,
			paddingRight: () => 2,
			paddingTop: (i: number) => (i === 0 ? 1 : 0),
			// Title row: ~1 pt under label (was 2 pt margin + 2 pt pad). Value row keeps bottom inset.
			paddingBottom: (i: number) => (i === 0 ? 1 : 2)
		}
	};
}

function buildBackstoryGrid(c: CoCCharacterData): any {
	const entries = backstoryPairsForPdf(c);
	const cols: any[] = [];

	for (let i = 0; i < entries.length; i += 2) {
		const rowIdx = i / 2;
		const left = entries[i];
		const right = entries[i + 1];

		cols.push({
			columns: [
				{ width: '*', stack: [backstoryCell(left, rowIdx, 0)] },
				{ width: 8, text: '' },
				{
					width: '*',
					stack: right ? [backstoryCell(right, rowIdx, 1)] : [{ text: '', fontSize: 1 }]
				}
			],
			margin: [0, 0, 0, 2] as [number, number, number, number]
		});
	}

	// Guardrail: keep the block bounded and predictable on one page.
	const MAX_VISUAL_ROWS = 4;
	return {
		stack: cols.slice(0, MAX_VISUAL_ROWS),
		margin: [0, 2, 0, 0] as [number, number, number, number]
	};
}
