/**
 * PDF export via pdfmake — two-page investigator sheet.
 * Original layout (not Chaosium trade dress).
 * CLIENT-SIDE only — pdfmake requires browser environment.
 */

import type { CoCCharacterData } from '$lib/types/character';
import { ALL_CHARACTERISTICS, CHARACTERISTIC_LABELS } from '$lib/types/common';
import { halfValue, fifthValue } from '$lib/engine/characteristics';

type Content = any;

let pdfMakeInstance: any = null;

async function getPdfMake() {
	if (pdfMakeInstance) return pdfMakeInstance;
	const pdfMake = (await import('pdfmake/build/pdfmake')).default;
	const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
	pdfMake.addVirtualFileSystem(pdfFonts);
	pdfMakeInstance = pdfMake;
	return pdfMake;
}

export async function generatePDF(
	character: CoCCharacterData,
	occupationName: string
): Promise<Uint8Array> {
	const c = character;

	const docDefinition: any = {
		pageSize: 'LETTER',
		pageMargins: [40, 40, 40, 60],
		footer: {
			text: 'This is unofficial Fan Content, not approved/endorsed by Chaosium. Call of Cthulhu is a registered trademark of Chaosium Inc. Generated by Miskatonic University Registrar.',
			fontSize: 6,
			margin: [40, 0, 40, 0],
			color: '#888888'
		},
		content: [
			// Page 1: Stats & Skills
			...buildPage1(c, occupationName),
			{ text: '', pageBreak: 'after' },
			// Page 2: Backstory & Equipment
			...buildPage2(c)
		],
		defaultStyle: {
			fontSize: 9,
			lineHeight: 1.3
		},
		styles: {
			title: { fontSize: 18, bold: true, margin: [0, 0, 0, 4] },
			subtitle: { fontSize: 10, color: '#555555', margin: [0, 0, 0, 12] },
			sectionHeader: { fontSize: 12, bold: true, margin: [0, 12, 0, 4], decoration: 'underline' },
			label: { fontSize: 7, color: '#888888', bold: true },
			statValue: { fontSize: 14, bold: true, alignment: 'center' as const },
			skillName: { fontSize: 8 },
			skillValue: { fontSize: 8, bold: true, alignment: 'right' as const }
		}
	};

	const pdfMake = await getPdfMake();
	const pdfDoc = pdfMake.createPdf(docDefinition);
	return await pdfDoc.getBuffer();
}

function buildPage1(c: CoCCharacterData, occupationName: string): Content[] {
	const content: Content[] = [];

	// Header
	content.push({ text: c.name || 'Unnamed Investigator', style: 'title' });
	content.push({
		text: `${occupationName} · Age ${c.age} · ${c.era} Era${c.residence ? ` · ${c.residence}` : ''}`,
		style: 'subtitle'
	});

	// Characteristics table
	content.push({ text: 'CHARACTERISTICS', style: 'sectionHeader' });
	const charRows = ALL_CHARACTERISTICS.map((charId) => {
		const v = c.characteristics.values[charId];
		return [
			{ text: CHARACTERISTIC_LABELS[charId].toUpperCase(), style: 'label' },
			{ text: String(v), style: 'statValue' },
			{ text: String(halfValue(v)), fontSize: 8, alignment: 'center' as const, color: '#666' },
			{ text: String(fifthValue(v)), fontSize: 8, alignment: 'center' as const, color: '#666' }
		];
	});

	content.push({
		table: {
			headerRows: 1,
			widths: [80, 40, 30, 30],
			body: [
				[
					{ text: '', style: 'label' },
					{ text: 'Value', style: 'label', alignment: 'center' as const },
					{ text: 'Half', style: 'label', alignment: 'center' as const },
					{ text: 'Fifth', style: 'label', alignment: 'center' as const }
				],
				...charRows
			]
		},
		layout: 'lightHorizontalLines'
	});

	// Derived stats
	content.push({ text: 'DERIVED ATTRIBUTES', style: 'sectionHeader' });
	content.push({
		columns: [
			{ text: `HP: ${c.derivedStats.hp.current}/${c.derivedStats.hp.max}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `MP: ${c.derivedStats.mp.current}/${c.derivedStats.mp.max}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `SAN: ${c.derivedStats.sanity.current}/${c.derivedStats.sanity.max}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `Luck: ${c.derivedStats.luck.current}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `DB: ${c.derivedStats.damageBonus}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `Build: ${c.derivedStats.build}`, width: 'auto', margin: [0, 0, 16, 0] },
			{ text: `MOV: ${c.derivedStats.moveRate}`, width: 'auto' }
		],
		margin: [0, 4, 0, 0] as [number, number, number, number]
	});

	// Skills
	if (c.skills.length > 0) {
		content.push({ text: 'SKILLS', style: 'sectionHeader' });

		const sorted = [...c.skills]
			.filter((s) => s.total > s.baseValue || s.isOccupation)
			.sort((a, b) => b.total - a.total);

		// Two-column skill list
		const mid = Math.ceil(sorted.length / 2);
		const leftSkills = sorted.slice(0, mid);
		const rightSkills = sorted.slice(mid);

		const formatSkill = (s: typeof sorted[0]) => {
			const name = s.skillId.replace(/-/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase());
			const marker = s.isOccupation ? '●' : '○';
			return [
				{ text: `${marker} ${name}`, style: 'skillName' },
				{ text: `${s.total}%`, style: 'skillValue' }
			];
		};

		const maxLen = Math.max(leftSkills.length, rightSkills.length);
		const skillBody = [];
		for (let i = 0; i < maxLen; i++) {
			const left = leftSkills[i] ? formatSkill(leftSkills[i]) : [{ text: '' }, { text: '' }];
			const right = rightSkills[i] ? formatSkill(rightSkills[i]) : [{ text: '' }, { text: '' }];
			skillBody.push([...left, { text: '' }, ...right]);
		}

		content.push({
			table: {
				widths: ['*', 30, 10, '*', 30],
				body: skillBody
			},
			layout: 'noBorders'
		});
	}

	return content;
}

function buildPage2(c: CoCCharacterData): Content[] {
	const content: Content[] = [];

	content.push({ text: `${c.name || 'Unnamed'} — Backstory & Equipment`, style: 'title' });

	// Backstory
	const backstoryFields = [
		['Ideology/Beliefs', c.backstory.ideologyBeliefs],
		['Significant People', c.backstory.significantPeople],
		['Meaningful Locations', c.backstory.meaningfulLocations],
		['Treasured Possessions', c.backstory.treasuredPossessions],
		['Traits', c.backstory.traits],
		['Injuries & Scars', c.backstory.injuriesScars],
		['Phobias & Manias', c.backstory.phobiasManias],
		['Arcane Tomes, Spells & Artifacts', c.backstory.arcaneTomesSpellsArtifacts],
		['Encounters with Strange Entities', c.backstory.encountersWithStrangeEntities],
		['Key Connection', c.backstory.keyConnection]
	].filter(([, v]) => v.trim());

	if (backstoryFields.length > 0) {
		content.push({ text: 'BACKSTORY', style: 'sectionHeader' });
		for (const [label, value] of backstoryFields) {
			content.push({ text: label.toUpperCase(), style: 'label', margin: [0, 6, 0, 1] as [number, number, number, number] });
			content.push({ text: value, margin: [0, 0, 0, 2] as [number, number, number, number] });
		}
	}

	// Equipment
	if (c.equipment.weapons.length > 0 || c.equipment.items.length > 0) {
		content.push({ text: 'EQUIPMENT & FINANCES', style: 'sectionHeader' });
		content.push({
			text: `Spending Level: ${c.equipment.spendingLevel} · Cash: $${c.equipment.cash.toLocaleString()} · Assets: ${c.equipment.assets}`,
			margin: [0, 0, 0, 6] as [number, number, number, number]
		});

		if (c.equipment.weapons.length > 0) {
			content.push({ text: 'WEAPONS', style: 'label', margin: [0, 4, 0, 2] as [number, number, number, number] });
			content.push({
				table: {
					headerRows: 1,
					widths: ['*', 60, 60, 40],
					body: [
						[
							{ text: 'Weapon', style: 'label' },
							{ text: 'Damage', style: 'label' },
							{ text: 'Range', style: 'label' },
							{ text: 'Attacks', style: 'label' }
						],
						...c.equipment.weapons.map((w) => [w.name, w.damage, w.range, w.attacksPerRound])
					]
				},
				layout: 'lightHorizontalLines'
			});
		}

		if (c.equipment.items.length > 0) {
			content.push({ text: 'ITEMS', style: 'label', margin: [0, 8, 0, 2] as [number, number, number, number] });
			content.push({ text: c.equipment.items.map((i) => i.name).join(', ') });
		}
	}

	return content;
}
