/**
 * One-page Letter PDF investigator sheet via pdfmake.
 * Original layout, no Chaosium trade dress. Client-side only.
 *
 * `buildDocDefinition` is pure — exported for unit testing without loading pdfmake.
 * `generatePDF` is the thin browser-only wrapper that actually renders.
 */

import type { CoCCharacterData } from '$lib/types/character';
import type {
	CoCSkillDefinition,
	CoCOccupationDefinition
} from '$lib/types/content-pack';
import { ALL_CHARACTERISTICS, CHARACTERISTIC_LABELS } from '$lib/types/common';
import { halfValue, fifthValue } from '$lib/engine/characteristics';
import {
	buildSkillRows,
	distributeIntoColumns,
	findOccupation,
	truncate,
	type SkillRow
} from './pdf-helpers';

// AA-safe text tokens (preserved from previous export).
const PDF_INK = '#1a1a1a';
const PDF_TEXT_SECONDARY = '#3a3a3a';
const PDF_LABEL = '#444444';
const PDF_FOOTER = '#555555';

// Period accent — burgundy banner fill, white uppercase text on top.
const PDF_BANNER_FILL = '#5C1A1B';
const PDF_BANNER_TEXT = '#ffffff';
const PDF_RULE = '#8a8a8a';
const PDF_BLANK_SLOT = '#777777';
// Zebra fill for skill rows — warm parchment, ~3% darker than white.
// Subtle in color, prints as a barely-perceptible gray in grayscale.
const PDF_ZEBRA = '#f6f0eb';

const DISCLAIMER =
	'This is unofficial Fan Content, not approved/endorsed by Chaosium. Call of Cthulhu is a registered trademark of Chaosium Inc. Generated by Miskatonic University Registrar.';

const SKILL_COLUMNS = 3;
const NAME_TRUNCATE = 48;
const BACKSTORY_TRUNCATE = 100;
const EQUIPMENT_TRUNCATE = 240;
const MAX_WEAPON_ROWS = 6;

let pdfMakeInstance: any = null;

async function getPdfMake() {
	if (pdfMakeInstance) return pdfMakeInstance;
	const pdfMake = (await import('pdfmake/build/pdfmake')).default;
	const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
	pdfMake.addVirtualFileSystem(pdfFonts);
	pdfMakeInstance = pdfMake;
	return pdfMake;
}

export async function generatePDF(
	character: CoCCharacterData,
	occupationName: string,
	skills: CoCSkillDefinition[],
	occupations: CoCOccupationDefinition[]
): Promise<Uint8Array> {
	const docDefinition = buildDocDefinition(character, occupationName, skills, occupations);
	const pdfMake = await getPdfMake();
	const pdfDoc = pdfMake.createPdf(docDefinition);
	return await pdfDoc.getBuffer();
}

export function buildDocDefinition(
	character: CoCCharacterData,
	occupationName: string,
	skills: CoCSkillDefinition[],
	occupations: CoCOccupationDefinition[]
): Record<string, unknown> {
	const occupation = findOccupation(occupations, character.occupation?.occupationId);
	const skillRows = buildSkillRows(character, skills, occupation);

	return {
		pageSize: 'LETTER',
		pageMargins: [28, 28, 28, 36],
		footer: {
			text: DISCLAIMER,
			fontSize: 6,
			margin: [28, 8, 28, 0],
			color: PDF_FOOTER,
			alignment: 'center' as const
		},
		content: [
			buildHeader(character, occupationName),
			{ text: '', margin: [0, 4, 0, 0] },
			buildStatsRow(character),
			{ text: '', margin: [0, 6, 0, 0] },
			buildSkillsSection(skillRows),
			{ text: '', margin: [0, 6, 0, 0] },
			buildWeaponsAndFinances(character)
		],
		defaultStyle: { fontSize: 8, lineHeight: 1.2, color: PDF_INK },
		styles: {
			titleName: { fontSize: 16, bold: true },
			subtitle: { fontSize: 8, color: PDF_TEXT_SECONDARY },
			banner: {
				fontSize: 8,
				bold: true,
				color: PDF_BANNER_TEXT,
				fillColor: PDF_BANNER_FILL,
				margin: [0, 0, 0, 0]
			},
			label: { fontSize: 6, color: PDF_LABEL, bold: true },
			statValue: { fontSize: 13, bold: true, alignment: 'center' as const },
			statSub: { fontSize: 7, color: PDF_TEXT_SECONDARY, alignment: 'center' as const },
			trackerValue: { fontSize: 11, bold: true, alignment: 'center' as const },
			trackerLabel: {
				fontSize: 6,
				color: PDF_LABEL,
				bold: true,
				alignment: 'center' as const
			},
			skillName: { fontSize: 8.5 },
			skillBlank: { fontSize: 8.5, italics: true, color: PDF_BLANK_SLOT },
			skillValue: { fontSize: 8.5, bold: true, alignment: 'right' as const },
			skillSub: { fontSize: 7, color: PDF_TEXT_SECONDARY, alignment: 'right' as const },
			fieldLabel: { fontSize: 6, color: PDF_LABEL, bold: true },
			fieldValue: { fontSize: 7.5 }
		}
	};
}

// --- Sections ---

function buildHeader(c: CoCCharacterData, occupationName: string) {
	const name = truncate(c.name || 'Unnamed Investigator', NAME_TRUNCATE);
	const subtitleParts = [
		occupationName,
		`Age ${c.age}`,
		`${c.era} Era`,
		c.residence,
		c.birthplace ? `b. ${c.birthplace}` : '',
		c.pronouns
	].filter(Boolean);

	return {
		stack: [
			{ text: name, style: 'titleName' },
			{ text: subtitleParts.join('  ·  '), style: 'subtitle' }
		]
	};
}

function bannerCell(text: string) {
	// Single-cell table that gives us a filled section header bar.
	return {
		table: {
			widths: ['*'],
			body: [[{ text: text.toUpperCase(), style: 'banner', margin: [4, 2, 4, 2] }]]
		},
		layout: {
			hLineWidth: () => 0,
			vLineWidth: () => 0,
			fillColor: () => PDF_BANNER_FILL
		},
		margin: [0, 0, 0, 2] as [number, number, number, number]
	};
}

function buildStatsRow(c: CoCCharacterData) {
	return {
		columns: [
			{ width: '*', stack: [bannerCell('Characteristics'), buildCharacteristicsTable(c)] },
			{ width: 12, text: '' },
			{
				width: '*',
				stack: [
					bannerCell('Attributes'),
					buildTrackersGrid(c),
					{ text: '', margin: [0, 6, 0, 0] as [number, number, number, number] },
					bannerCell('Backstory'),
					...buildBackstoryRows(c)
				]
			}
		]
	};
}

function buildCharacteristicsTable(c: CoCCharacterData) {
	const headerCellStyle = {
		fontSize: 8,
		color: PDF_LABEL,
		bold: true,
		alignment: 'center' as const
	};
	const headerRow = [
		// Top-left "unused" corner — burgundy fill ties it back to the section banner.
		{ text: '', fillColor: PDF_BANNER_FILL },
		{ text: 'Reg', ...headerCellStyle },
		{ text: 'Half', ...headerCellStyle },
		{ text: 'Fifth', ...headerCellStyle }
	];
	// Vertical centering: the regular value (statValue, fontSize 13) drives row
	// height. Smaller cells get a top margin = (rowHeight - cellHeight) / 2 so
	// they read as centered rather than top-aligned.
	const body = [
		headerRow,
		...ALL_CHARACTERISTICS.map((id) => {
			const v = c.characteristics.values[id];
			return [
				{
					text: CHARACTERISTIC_LABELS[id],
					fontSize: 11,
					bold: true,
					alignment: 'center' as const,
					margin: [0, 2, 0, 0] as [number, number, number, number]
				},
				{ text: String(v), style: 'statValue' },
				{
					text: String(halfValue(v)),
					fontSize: 12,
					alignment: 'center' as const,
					color: PDF_TEXT_SECONDARY,
					margin: [0, 1, 0, 0] as [number, number, number, number]
				},
				{
					text: String(fifthValue(v)),
					fontSize: 12,
					alignment: 'center' as const,
					color: PDF_TEXT_SECONDARY,
					margin: [0, 1, 0, 0] as [number, number, number, number]
				}
			];
		})
	];

	return {
		table: { widths: [90, '*', 30, 30], body },
		layout: {
			hLineWidth: () => 0.5,
			vLineWidth: () => 0.5,
			hLineColor: () => PDF_RULE,
			vLineColor: () => PDF_RULE,
			paddingLeft: () => 2,
			paddingRight: () => 2,
			paddingTop: () => 1,
			paddingBottom: () => 1
		}
	};
}

function trackerBox(label: string, current: number | string, max?: number | string) {
	const valueText =
		max !== undefined && max !== '' ? `${current} / ${max}` : String(current);
	return {
		table: {
			widths: ['*'],
			body: [
				[{ text: label.toUpperCase(), style: 'trackerLabel', margin: [0, 2, 0, 0] }],
				[{ text: valueText, style: 'trackerValue', margin: [0, 0, 0, 3] }]
			]
		},
		layout: {
			hLineWidth: () => 0.75,
			vLineWidth: () => 0.75,
			hLineColor: () => PDF_INK,
			vLineColor: () => PDF_INK
		}
	};
}

function buildTrackersGrid(c: CoCCharacterData) {
	const d = c.derivedStats;
	const cell = (col: any) => ({ width: '*', stack: [col] });

	return {
		stack: [
			{
				columns: [
					cell(trackerBox('Hit Points', d.hp.current, d.hp.max)),
					{ width: 6, text: '' },
					cell(trackerBox('Magic Points', d.mp.current, d.mp.max)),
					{ width: 6, text: '' },
					cell(trackerBox('Sanity', d.sanity.current, d.sanity.max))
				],
				margin: [0, 0, 0, 4] as [number, number, number, number]
			},
			{
				columns: [
					cell(trackerBox('Luck', d.luck.current)),
					{ width: 4, text: '' },
					cell(trackerBox('Damage Bonus', d.damageBonus)),
					{ width: 4, text: '' },
					cell(trackerBox('Build', d.build)),
					{ width: 4, text: '' },
					cell(trackerBox('Move', d.moveRate))
				]
			}
		]
	};
}

function formatRowName(row: SkillRow): string {
	const marker = row.isOccupation ? '● ' : row.isImproved ? '◐ ' : '○ ';
	return marker + row.displayName;
}

function buildSkillsSection(rows: SkillRow[]) {
	const columns = distributeIntoColumns(rows, SKILL_COLUMNS);

	const renderColumn = (colRows: SkillRow[]) => {
		const body: Array<Array<{ text: string; style: string }>> = colRows.map((row) => [
			{
				text: formatRowName(row),
				style: row.isBlankSlot ? 'skillBlank' : 'skillName'
			},
			{ text: `${row.value}`, style: 'skillValue' },
			{ text: `${halfValue(row.value)}`, style: 'skillSub' },
			{ text: `${fifthValue(row.value)}`, style: 'skillSub' }
		]);
		// Pad shorter columns to keep heights aligned.
		const targetLength = Math.max(...columns.map((c) => c.length));
		while (body.length < targetLength) {
			body.push([
				{ text: '', style: 'skillName' },
				{ text: '', style: 'skillValue' },
				{ text: '', style: 'skillSub' },
				{ text: '', style: 'skillSub' }
			]);
		}
		return {
			table: { widths: ['*', 18, 14, 14], body },
			layout: {
				hLineWidth: () => 0,
				vLineWidth: () => 0,
				fillColor: (rowIndex: number) =>
					rowIndex % 2 === 1 ? PDF_ZEBRA : null,
				paddingLeft: () => 3,
				paddingRight: () => 3,
				paddingTop: () => 1,
				paddingBottom: () => 1
			}
		};
	};

	const cols: any[] = [];
	columns.forEach((col, i) => {
		cols.push({ width: '*', stack: [renderColumn(col)] });
		if (i < columns.length - 1) cols.push({ width: 6, text: '' });
	});

	return { stack: [bannerCell('Investigator Skills'), { columns: cols }] };
}

function buildWeaponsAndFinances(c: CoCCharacterData) {
	const eq = c.equipment;
	const stack: any[] = [bannerCell('Combat & Possessions')];

	const weaponRows = eq.weapons.slice(0, MAX_WEAPON_ROWS);
	const overflow = eq.weapons.length - weaponRows.length;
	const weaponBody = [
		[
			{ text: 'Weapon', style: 'label' },
			{ text: 'Damage', style: 'label' },
			{ text: 'Range', style: 'label' },
			{ text: 'Atk', style: 'label' }
		],
		...weaponRows.map((w) => [
			{ text: truncate(w.name, 28), fontSize: 7 },
			{ text: w.damage, fontSize: 7 },
			{ text: w.range, fontSize: 7 },
			{ text: w.attacksPerRound, fontSize: 7 }
		])
	];
	if (overflow > 0) {
		weaponBody.push([
			{ text: `+${overflow} more weapon${overflow === 1 ? '' : 's'} not shown`, fontSize: 6, color: PDF_FOOTER, italics: true } as any,
			{ text: '' },
			{ text: '' },
			{ text: '' }
		]);
	}

	if (weaponRows.length > 0) {
		stack.push({
			table: { widths: ['*', 60, 50, 30], body: weaponBody },
			layout: {
				hLineWidth: () => 0.25,
				vLineWidth: () => 0.25,
				hLineColor: () => PDF_RULE,
				vLineColor: () => PDF_RULE,
				paddingLeft: () => 3,
				paddingRight: () => 3,
				paddingTop: () => 1,
				paddingBottom: () => 1
			},
			margin: [0, 0, 0, 4] as [number, number, number, number]
		});
	}

	const financeParts = [
		eq.livingStandard ? `Living: ${eq.livingStandard}` : '',
		eq.spendingLevel ? `Spend: $${eq.spendingLevel.toLocaleString()}` : '',
		`Cash: $${(eq.cash || 0).toLocaleString()}`,
		eq.assetsLabel ? `Assets: ${eq.assetsLabel}` : ''
	].filter(Boolean);

	stack.push({
		columns: [
			{ text: 'FINANCES', style: 'fieldLabel', width: 50 },
			{ text: financeParts.join('  ·  '), style: 'fieldValue' }
		],
		margin: [0, 0, 0, 3] as [number, number, number, number]
	});

	if (eq.items.length > 0) {
		const itemList = truncate(eq.items.map((i) => i.name).join(', '), EQUIPMENT_TRUNCATE);
		stack.push({
			columns: [
				{ text: 'GEAR', style: 'fieldLabel', width: 50 },
				{ text: itemList, style: 'fieldValue' }
			]
		});
	}

	return { stack };
}

const BACKSTORY_FIELDS: Array<[label: string, key: keyof CoCCharacterData['backstory']]> = [
	['Ideology / Beliefs', 'ideologyBeliefs'],
	['Significant People', 'significantPeople'],
	['Traits', 'traits'],
	['Key Connection', 'keyConnection']
];

function buildBackstoryRows(c: CoCCharacterData): any[] {
	return BACKSTORY_FIELDS.map(([label, key]) => ({
		columns: [
			{ text: label.toUpperCase(), style: 'fieldLabel', width: 65 },
			{ text: truncate(c.backstory[key] || '—', BACKSTORY_TRUNCATE), style: 'fieldValue' }
		],
		margin: [0, 1, 0, 1] as [number, number, number, number]
	}));
}
